# Using the official Python 3.12 slim image as the base image
FROM python:3.12-slim

# Set the working directory inside the container to /app
WORKDIR /app

# Copy the application file (app.py) into the working directory
COPY ./app/app.py .

# Define the default command to run the application
CMD ["python", "app.py"]


